package com.bariumhoof.bgfx4j.enums;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_CAPS {
    ALPHA_TO_COVERAGE(BGFX_CAPS_ALPHA_TO_COVERAGE),
    BLEND_INDEPENDENT(BGFX_CAPS_BLEND_INDEPENDENT),
    COMPUTE(BGFX_CAPS_COMPUTE),
    CONSERVATIVE_RASTER(BGFX_CAPS_CONSERVATIVE_RASTER),
    DRAW_INDIRECT(BGFX_CAPS_DRAW_INDIRECT),
    FRAGMENT_DEPTH(BGFX_CAPS_FRAGMENT_DEPTH),
    FRAGMENT_ORDERING(BGFX_CAPS_FRAGMENT_ORDERING),
    FRAMEBUFFER_RW(BGFX_CAPS_FRAMEBUFFER_RW),
    GRAPHICS_DEBUGGER(BGFX_CAPS_GRAPHICS_DEBUGGER),
    HDR10(BGFX_CAPS_HDR10),
    HIDPI(BGFX_CAPS_HIDPI),
    INDEX32(BGFX_CAPS_INDEX32),
    INSTANCING(BGFX_CAPS_INSTANCING),
    OCCLUSION_QUERY(BGFX_CAPS_OCCLUSION_QUERY),
    RENDERER_MULTITHREADED(BGFX_CAPS_RENDERER_MULTITHREADED),
    SWAP_CHAIN(BGFX_CAPS_SWAP_CHAIN),
    TEXTURE_2D_ARRAY(BGFX_CAPS_TEXTURE_2D_ARRAY),
    TEXTURE_3D(BGFX_CAPS_TEXTURE_3D),
    TEXTURE_BLIT(BGFX_CAPS_TEXTURE_BLIT),
    TEXTURE_COMPARE_ALL(BGFX_CAPS_TEXTURE_COMPARE_ALL),
    TEXTURE_COMPARE_LEQUAL(BGFX_CAPS_TEXTURE_COMPARE_LEQUAL),
    TEXTURE_CUBE_ARRAY(BGFX_CAPS_TEXTURE_CUBE_ARRAY),
    TEXTURE_DIRECT_ACCESS(BGFX_CAPS_TEXTURE_DIRECT_ACCESS),
    TEXTURE_READ_BACK(BGFX_CAPS_TEXTURE_READ_BACK),
    VERTEX_ATTRIB_HALF(BGFX_CAPS_VERTEX_ATTRIB_HALF),
    VERTEX_ATTRIB_UINT10(BGFX_CAPS_VERTEX_ATTRIB_UINT10),
    VERTEX_ID(BGFX_CAPS_VERTEX_ID);

    public final long VALUE;

    BGFX_CAPS(long value) {
        this.VALUE = value;
    }
}