package com.bariumhoof.bgfx4j.enums;

import java.util.Set;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_RESET {
    NONE(BGFX_RESET_NONE),
    FULLSCREEN(BGFX_RESET_FULLSCREEN),
    FULLSCREEN_SHIFT(BGFX_RESET_FULLSCREEN_SHIFT),
    FULLSCREEN_MASK(BGFX_RESET_FULLSCREEN_MASK),
    MSAA_X2(BGFX_RESET_MSAA_X2),
    MSAA_X4(BGFX_RESET_MSAA_X4),
    MSAA_X8(BGFX_RESET_MSAA_X8),
    MSAA_X16(BGFX_RESET_MSAA_X16),
    MSAA_SHIFT(BGFX_RESET_MSAA_SHIFT),
    MSAA_MASK(BGFX_RESET_MSAA_MASK),
    VSYNC(BGFX_RESET_VSYNC),
    MAXANISOTROPY(BGFX_RESET_MAXANISOTROPY),
    CAPTURE(BGFX_RESET_CAPTURE),
    FLUSH_AFTER_RENDER(BGFX_RESET_FLUSH_AFTER_RENDER),
    FLIP_AFTER_RENDER(BGFX_RESET_FLIP_AFTER_RENDER),
    SRGB_BACKBUFFER(BGFX_RESET_SRGB_BACKBUFFER),
    HDR10(BGFX_RESET_HDR10),
    HIDPI(BGFX_RESET_HIDPI),
    DEPTH_CLAMP(BGFX_RESET_DEPTH_CLAMP),
    SUSPEND(BGFX_RESET_SUSPEND);

    public final int VALUE;

    BGFX_RESET(int value) {
        this.VALUE = value;
    }

    public static long flags(Set<BGFX_RESET> states) {
        long bits = 0L;
        for (BGFX_RESET next : states) {
            bits |= next.VALUE;
        }
        return bits;
    }
}
