package com.bariumhoof.bgfx4j.enums;

import java.util.Set;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_BUFFER_COMPUTE {
    FORMAT_8x1(BGFX_BUFFER_COMPUTE_FORMAT_8x1),
    FORMAT_8x2(BGFX_BUFFER_COMPUTE_FORMAT_8x2),
    FORMAT_8x4(BGFX_BUFFER_COMPUTE_FORMAT_8x4),
    FORMAT_16x1(BGFX_BUFFER_COMPUTE_FORMAT_16x1),
    FORMAT_16x2(BGFX_BUFFER_COMPUTE_FORMAT_16x2),
    FORMAT_16x4(BGFX_BUFFER_COMPUTE_FORMAT_16x4),
    FORMAT_32x1(BGFX_BUFFER_COMPUTE_FORMAT_32x1),
    FORMAT_32x2(BGFX_BUFFER_COMPUTE_FORMAT_32x2),
    FORMAT_32x4(BGFX_BUFFER_COMPUTE_FORMAT_32x4),
    FORMAT_SHIFT(BGFX_BUFFER_COMPUTE_FORMAT_SHIFT),
    FORMAT_MASK(BGFX_BUFFER_COMPUTE_FORMAT_MASK),
    TYPE_INT(BGFX_BUFFER_COMPUTE_TYPE_INT),
    TYPE_UINT(BGFX_BUFFER_COMPUTE_TYPE_UINT),
    TYPE_FLOAT(BGFX_BUFFER_COMPUTE_TYPE_FLOAT),
    TYPE_SHIFT(BGFX_BUFFER_COMPUTE_TYPE_SHIFT),
    TYPE_MASK(BGFX_BUFFER_COMPUTE_TYPE_MASK);

    public final short VALUE;

    BGFX_BUFFER_COMPUTE(short value) {
        this.VALUE = value;
    }

    public static long flags(Set<BGFX_BUFFER_COMPUTE> states) {
        long bits = 0L;
        for (BGFX_BUFFER_COMPUTE next : states) {
            bits |= next.VALUE;
        }
        return bits;
    }
}
