package com.bariumhoof.bgfx4j.enums;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_STATE {
    WRITE_R(BGFX_STATE_WRITE_R),
    WRITE_G(BGFX_STATE_WRITE_G),
    WRITE_B(BGFX_STATE_WRITE_B),
    WRITE_A(BGFX_STATE_WRITE_A),
    WRITE_Z(BGFX_STATE_WRITE_Z),
    WRITE_RGB(BGFX_STATE_WRITE_RGB),
    WRITE_MASK(BGFX_STATE_WRITE_MASK),
    DEPTH_TEST_LESS(BGFX_STATE_DEPTH_TEST_LESS),
    DEPTH_TEST_LEQUAL(BGFX_STATE_DEPTH_TEST_LEQUAL),
    DEPTH_TEST_EQUAL(BGFX_STATE_DEPTH_TEST_EQUAL),
    DEPTH_TEST_GEQUAL(BGFX_STATE_DEPTH_TEST_GEQUAL),
    DEPTH_TEST_GREATER(BGFX_STATE_DEPTH_TEST_GREATER),
    DEPTH_TEST_NOTEQUAL(BGFX_STATE_DEPTH_TEST_NOTEQUAL),
    DEPTH_TEST_NEVER(BGFX_STATE_DEPTH_TEST_NEVER),
    DEPTH_TEST_ALWAYS(BGFX_STATE_DEPTH_TEST_ALWAYS),
    BLEND_ZERO(BGFX_STATE_BLEND_ZERO),
    BLEND_ONE(BGFX_STATE_BLEND_ONE),
    BLEND_SRC_COLOR(BGFX_STATE_BLEND_SRC_COLOR),
    BLEND_INV_SRC_COLOR(BGFX_STATE_BLEND_INV_SRC_COLOR),
    BLEND_SRC_ALPHA(BGFX_STATE_BLEND_SRC_ALPHA),
    BLEND_INV_SRC_ALPHA(BGFX_STATE_BLEND_INV_SRC_ALPHA),
    BLEND_DST_ALPHA(BGFX_STATE_BLEND_DST_ALPHA),
    BLEND_INV_DST_ALPHA(BGFX_STATE_BLEND_INV_DST_ALPHA),
    BLEND_DST_COLOR(BGFX_STATE_BLEND_DST_COLOR),
    BLEND_INV_DST_COLOR(BGFX_STATE_BLEND_INV_DST_COLOR),
    BLEND_SRC_ALPHA_SAT(BGFX_STATE_BLEND_SRC_ALPHA_SAT),
    BLEND_FACTOR(BGFX_STATE_BLEND_FACTOR),
    BLEND_INV_FACTOR(BGFX_STATE_BLEND_INV_FACTOR),
    BLEND_EQUATION_ADD(BGFX_STATE_BLEND_EQUATION_ADD),
    BLEND_EQUATION_SUB(BGFX_STATE_BLEND_EQUATION_SUB),
    BLEND_EQUATION_REVSUB(BGFX_STATE_BLEND_EQUATION_REVSUB),
    BLEND_EQUATION_MIN(BGFX_STATE_BLEND_EQUATION_MIN),
    BLEND_EQUATION_MAX(BGFX_STATE_BLEND_EQUATION_MAX),
    BLEND_INDEPENDENT(BGFX_STATE_BLEND_INDEPENDENT),
    BLEND_ALPHA_TO_COVERAGE(BGFX_STATE_BLEND_ALPHA_TO_COVERAGE),
    CULL_CW(BGFX_STATE_CULL_CW),
    CULL_CCW(BGFX_STATE_CULL_CCW),
    PT_TRISTRIP(BGFX_STATE_PT_TRISTRIP),
    PT_LINES(BGFX_STATE_PT_LINES),
    PT_LINESTRIP(BGFX_STATE_PT_LINESTRIP),
    PT_POINTS(BGFX_STATE_PT_POINTS),
    MSAA(BGFX_STATE_MSAA),
    LINEAA(BGFX_STATE_LINEAA),
    CONSERVATIVE_RASTER(BGFX_STATE_CONSERVATIVE_RASTER),
    NONE(BGFX_STATE_NONE),
    DEFAULT(BGFX_STATE_DEFAULT);

    public final long VALUE;

    BGFX_STATE(long value) {
        this.VALUE = value;
    }
}