package com.bariumhoof.bgfx4j.enums;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_SAMPLER {
    NONE(BGFX_SAMPLER_NONE),
    U_MIRROR(BGFX_SAMPLER_U_MIRROR),
    U_CLAMP(BGFX_SAMPLER_U_CLAMP),
    U_BORDER(BGFX_SAMPLER_U_BORDER),
    V_MIRROR(BGFX_SAMPLER_V_MIRROR),
    V_CLAMP(BGFX_SAMPLER_V_CLAMP),
    V_BORDER(BGFX_SAMPLER_V_BORDER),
    W_MIRROR(BGFX_SAMPLER_W_MIRROR),
    W_CLAMP(BGFX_SAMPLER_W_CLAMP),
    W_BORDER(BGFX_SAMPLER_W_BORDER),
    UVW_MIRROR(BGFX_SAMPLER_UVW_MIRROR),
    UVW_CLAMP(BGFX_SAMPLER_UVW_CLAMP),
    UVW_BORDER(BGFX_SAMPLER_UVW_BORDER),
    MIN_POINT(BGFX_SAMPLER_MIN_POINT),
    MIN_ANISOTROPIC(BGFX_SAMPLER_MIN_ANISOTROPIC),
    MAG_POINT(BGFX_SAMPLER_MAG_POINT),
    MAG_ANISOTROPIC(BGFX_SAMPLER_MAG_ANISOTROPIC),
    MIP_POINT(BGFX_SAMPLER_MIP_POINT),
    POINT(BGFX_SAMPLER_POINT),
    COMPARE_LESS(BGFX_SAMPLER_COMPARE_LESS),
    COMPARE_LEQUAL(BGFX_SAMPLER_COMPARE_LEQUAL),
    COMPARE_EQUAL(BGFX_SAMPLER_COMPARE_EQUAL),
    COMPARE_GEQUAL(BGFX_SAMPLER_COMPARE_GEQUAL),
    COMPARE_GREATER(BGFX_SAMPLER_COMPARE_GREATER),
    COMPARE_NOTEQUAL(BGFX_SAMPLER_COMPARE_NOTEQUAL),
    COMPARE_NEVER(BGFX_SAMPLER_COMPARE_NEVER),
    COMPARE_ALWAYS(BGFX_SAMPLER_COMPARE_ALWAYS),
    SAMPLE_STENCIL(BGFX_SAMPLER_SAMPLE_STENCIL);

    public final int VALUE;

    BGFX_SAMPLER(int value) {
        this.VALUE = value;
    }
}