package com.bariumhoof.bgfx4j.enums;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_STENCIL {
    TEST_LESS(BGFX_STENCIL_TEST_LESS),
    TEST_LEQUAL(BGFX_STENCIL_TEST_LEQUAL),
    TEST_EQUAL(BGFX_STENCIL_TEST_EQUAL),
    TEST_GEQUAL(BGFX_STENCIL_TEST_GEQUAL),
    TEST_GREATER(BGFX_STENCIL_TEST_GREATER),
    TEST_NOTEQUAL(BGFX_STENCIL_TEST_NOTEQUAL),
    TEST_NEVER(BGFX_STENCIL_TEST_NEVER),
    TEST_ALWAYS(BGFX_STENCIL_TEST_ALWAYS),
    OP_FAIL_S_ZERO(BGFX_STENCIL_OP_FAIL_S_ZERO),
    OP_FAIL_S_KEEP(BGFX_STENCIL_OP_FAIL_S_KEEP),
    OP_FAIL_S_REPLACE(BGFX_STENCIL_OP_FAIL_S_REPLACE),
    OP_FAIL_S_INCR(BGFX_STENCIL_OP_FAIL_S_INCR),
    OP_FAIL_S_INCRSAT(BGFX_STENCIL_OP_FAIL_S_INCRSAT),
    OP_FAIL_S_DECR(BGFX_STENCIL_OP_FAIL_S_DECR),
    OP_FAIL_S_DECRSAT(BGFX_STENCIL_OP_FAIL_S_DECRSAT),
    OP_FAIL_S_INVERT(BGFX_STENCIL_OP_FAIL_S_INVERT),
    OP_FAIL_Z_ZERO(BGFX_STENCIL_OP_FAIL_Z_ZERO),
    OP_FAIL_Z_KEEP(BGFX_STENCIL_OP_FAIL_Z_KEEP),
    OP_FAIL_Z_REPLACE(BGFX_STENCIL_OP_FAIL_Z_REPLACE),
    OP_FAIL_Z_INCR(BGFX_STENCIL_OP_FAIL_Z_INCR),
    OP_FAIL_Z_INCRSAT(BGFX_STENCIL_OP_FAIL_Z_INCRSAT),
    OP_FAIL_Z_DECR(BGFX_STENCIL_OP_FAIL_Z_DECR),
    OP_FAIL_Z_DECRSAT(BGFX_STENCIL_OP_FAIL_Z_DECRSAT),
    OP_FAIL_Z_INVERT(BGFX_STENCIL_OP_FAIL_Z_INVERT),
    OP_PASS_Z_ZERO(BGFX_STENCIL_OP_PASS_Z_ZERO),
    OP_PASS_Z_KEEP(BGFX_STENCIL_OP_PASS_Z_KEEP),
    OP_PASS_Z_REPLACE(BGFX_STENCIL_OP_PASS_Z_REPLACE),
    OP_PASS_Z_INCR(BGFX_STENCIL_OP_PASS_Z_INCR),
    OP_PASS_Z_INCRSAT(BGFX_STENCIL_OP_PASS_Z_INCRSAT),
    OP_PASS_Z_DECR(BGFX_STENCIL_OP_PASS_Z_DECR),
    OP_PASS_Z_DECRSAT(BGFX_STENCIL_OP_PASS_Z_DECRSAT),
    OP_PASS_Z_INVERT(BGFX_STENCIL_OP_PASS_Z_INVERT),
    NONE(BGFX_STENCIL_NONE),
    DEFAULT(BGFX_STENCIL_DEFAULT);

    public final int VALUE;

    BGFX_STENCIL(int value) {
        this.VALUE = value;
    }
}