package com.bariumhoof.bgfx4j.enums;

import java.util.Set;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_TEXTURE_FORMAT {
    BC1(BGFX_TEXTURE_FORMAT_BC1),
    BC2(BGFX_TEXTURE_FORMAT_BC2),
    BC3(BGFX_TEXTURE_FORMAT_BC3),
    BC4(BGFX_TEXTURE_FORMAT_BC4),
    BC5(BGFX_TEXTURE_FORMAT_BC5),
    BC6H(BGFX_TEXTURE_FORMAT_BC6H),
    BC7(BGFX_TEXTURE_FORMAT_BC7),
    ETC1(BGFX_TEXTURE_FORMAT_ETC1),
    ETC2(BGFX_TEXTURE_FORMAT_ETC2),
    ETC2A(BGFX_TEXTURE_FORMAT_ETC2A),
    ETC2A1(BGFX_TEXTURE_FORMAT_ETC2A1),
    PTC12(BGFX_TEXTURE_FORMAT_PTC12),
    PTC14(BGFX_TEXTURE_FORMAT_PTC14),
    PTC12A(BGFX_TEXTURE_FORMAT_PTC12A),
    PTC14A(BGFX_TEXTURE_FORMAT_PTC14A),
    PTC22(BGFX_TEXTURE_FORMAT_PTC22),
    PTC24(BGFX_TEXTURE_FORMAT_PTC24),
    ATC(BGFX_TEXTURE_FORMAT_ATC),
    ATCE(BGFX_TEXTURE_FORMAT_ATCE),
    ATCI(BGFX_TEXTURE_FORMAT_ATCI),
    ASTC4x4(BGFX_TEXTURE_FORMAT_ASTC4x4),
    ASTC5x5(BGFX_TEXTURE_FORMAT_ASTC5x5),
    ASTC6x6(BGFX_TEXTURE_FORMAT_ASTC6x6),
    ASTC8x5(BGFX_TEXTURE_FORMAT_ASTC8x5),
    ASTC8x6(BGFX_TEXTURE_FORMAT_ASTC8x6),
    ASTC10x5(BGFX_TEXTURE_FORMAT_ASTC10x5),
    UNKNOWN(BGFX_TEXTURE_FORMAT_UNKNOWN),
    R1(BGFX_TEXTURE_FORMAT_R1),
    A8(BGFX_TEXTURE_FORMAT_A8),
    R8(BGFX_TEXTURE_FORMAT_R8),
    R8I(BGFX_TEXTURE_FORMAT_R8I),
    R8U(BGFX_TEXTURE_FORMAT_R8U),
    R8S(BGFX_TEXTURE_FORMAT_R8S),
    R16(BGFX_TEXTURE_FORMAT_R16),
    R16I(BGFX_TEXTURE_FORMAT_R16I),
    R16U(BGFX_TEXTURE_FORMAT_R16U),
    R16F(BGFX_TEXTURE_FORMAT_R16F),
    R16S(BGFX_TEXTURE_FORMAT_R16S),
    R32I(BGFX_TEXTURE_FORMAT_R32I),
    R32U(BGFX_TEXTURE_FORMAT_R32U),
    R32F(BGFX_TEXTURE_FORMAT_R32F),
    RG8(BGFX_TEXTURE_FORMAT_RG8),
    RG8I(BGFX_TEXTURE_FORMAT_RG8I),
    RG8U(BGFX_TEXTURE_FORMAT_RG8U),
    RG8S(BGFX_TEXTURE_FORMAT_RG8S),
    RG16(BGFX_TEXTURE_FORMAT_RG16),
    RG16I(BGFX_TEXTURE_FORMAT_RG16I),
    RG16U(BGFX_TEXTURE_FORMAT_RG16U),
    RG16F(BGFX_TEXTURE_FORMAT_RG16F),
    RG16S(BGFX_TEXTURE_FORMAT_RG16S),
    RG32I(BGFX_TEXTURE_FORMAT_RG32I),
    RG32U(BGFX_TEXTURE_FORMAT_RG32U),
    RG32F(BGFX_TEXTURE_FORMAT_RG32F),
    RGB8(BGFX_TEXTURE_FORMAT_RGB8),
    RGB8I(BGFX_TEXTURE_FORMAT_RGB8I),
    RGB8U(BGFX_TEXTURE_FORMAT_RGB8U),
    RGB8S(BGFX_TEXTURE_FORMAT_RGB8S),
    RGB9E5F(BGFX_TEXTURE_FORMAT_RGB9E5F),
    BGRA8(BGFX_TEXTURE_FORMAT_BGRA8),
    RGBA8(BGFX_TEXTURE_FORMAT_RGBA8),
    RGBA8I(BGFX_TEXTURE_FORMAT_RGBA8I),
    RGBA8U(BGFX_TEXTURE_FORMAT_RGBA8U),
    RGBA8S(BGFX_TEXTURE_FORMAT_RGBA8S),
    RGBA16(BGFX_TEXTURE_FORMAT_RGBA16),
    RGBA16I(BGFX_TEXTURE_FORMAT_RGBA16I),
    RGBA16U(BGFX_TEXTURE_FORMAT_RGBA16U),
    RGBA16F(BGFX_TEXTURE_FORMAT_RGBA16F),
    RGBA16S(BGFX_TEXTURE_FORMAT_RGBA16S),
    RGBA32I(BGFX_TEXTURE_FORMAT_RGBA32I),
    RGBA32U(BGFX_TEXTURE_FORMAT_RGBA32U),
    RGBA32F(BGFX_TEXTURE_FORMAT_RGBA32F),
    R5G6B5(BGFX_TEXTURE_FORMAT_R5G6B5),
    RGBA4(BGFX_TEXTURE_FORMAT_RGBA4),
    RGB5A1(BGFX_TEXTURE_FORMAT_RGB5A1),
    RGB10A2(BGFX_TEXTURE_FORMAT_RGB10A2),
    RG11B10F(BGFX_TEXTURE_FORMAT_RG11B10F),
    UNKNOWN_DEPTH(BGFX_TEXTURE_FORMAT_UNKNOWN_DEPTH),
    D16(BGFX_TEXTURE_FORMAT_D16),
    D24(BGFX_TEXTURE_FORMAT_D24),
    D24S8(BGFX_TEXTURE_FORMAT_D24S8),
    D32(BGFX_TEXTURE_FORMAT_D32),
    D16F(BGFX_TEXTURE_FORMAT_D16F),
    D24F(BGFX_TEXTURE_FORMAT_D24F),
    D32F(BGFX_TEXTURE_FORMAT_D32F),
    D0S8(BGFX_TEXTURE_FORMAT_D0S8),
    COUNT(BGFX_TEXTURE_FORMAT_COUNT);

    public final int VALUE;

    BGFX_TEXTURE_FORMAT(int value) {
        this.VALUE = value;
    }

    public static long flags(Set<BGFX_TEXTURE_FORMAT> states) {
        long bits = 0L;
        for (BGFX_TEXTURE_FORMAT next : states) {
            bits |= next.VALUE;
        }
        return bits;
    }
}
