package com.bariumhoof.bgfx4j.enums;

import java.util.Set;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_ATTRIB {
    POSITION(BGFX_ATTRIB_POSITION),
    NORMAL(BGFX_ATTRIB_NORMAL),
    TANGENT(BGFX_ATTRIB_TANGENT),
    BITANGENT(BGFX_ATTRIB_BITANGENT),
    COLOR0(BGFX_ATTRIB_COLOR0),
    COLOR1(BGFX_ATTRIB_COLOR1),
    COLOR2(BGFX_ATTRIB_COLOR2),
    COLOR3(BGFX_ATTRIB_COLOR3),
    INDICES(BGFX_ATTRIB_INDICES),
    WEIGHT(BGFX_ATTRIB_WEIGHT),
    TEXCOORD0(BGFX_ATTRIB_TEXCOORD0),
    TEXCOORD1(BGFX_ATTRIB_TEXCOORD1),
    TEXCOORD2(BGFX_ATTRIB_TEXCOORD2),
    TEXCOORD3(BGFX_ATTRIB_TEXCOORD3),
    TEXCOORD4(BGFX_ATTRIB_TEXCOORD4),
    TEXCOORD5(BGFX_ATTRIB_TEXCOORD5),
    TEXCOORD6(BGFX_ATTRIB_TEXCOORD6),
    TEXCOORD7(BGFX_ATTRIB_TEXCOORD7),
    COUNT(BGFX_ATTRIB_COUNT);

    public final int VALUE;

    BGFX_ATTRIB(int value) {
        this.VALUE = value;
    }

    public static long flags(Set<BGFX_ATTRIB> states) {
        long bits = 0L;
        for (BGFX_ATTRIB next : states) {
            bits |= next.VALUE;
        }
        return bits;
    }
}
