package com.bariumhoof.bgfx4j.enums;

import java.util.Set;

import static org.lwjgl.bgfx.BGFX.*;

public enum BGFX_TOPOLOGY_SORT {
    DIRECTION_FRONT_TO_BACK_MIN(BGFX_TOPOLOGY_SORT_DIRECTION_FRONT_TO_BACK_MIN),
    DIRECTION_FRONT_TO_BACK_AVG(BGFX_TOPOLOGY_SORT_DIRECTION_FRONT_TO_BACK_AVG),
    DIRECTION_FRONT_TO_BACK_MAX(BGFX_TOPOLOGY_SORT_DIRECTION_FRONT_TO_BACK_MAX),
    DIRECTION_BACK_TO_FRONT_MIN(BGFX_TOPOLOGY_SORT_DIRECTION_BACK_TO_FRONT_MIN),
    DIRECTION_BACK_TO_FRONT_AVG(BGFX_TOPOLOGY_SORT_DIRECTION_BACK_TO_FRONT_AVG),
    DIRECTION_BACK_TO_FRONT_MAX(BGFX_TOPOLOGY_SORT_DIRECTION_BACK_TO_FRONT_MAX),
    DISTANCE_FRONT_TO_BACK_MIN(BGFX_TOPOLOGY_SORT_DISTANCE_FRONT_TO_BACK_MIN),
    DISTANCE_FRONT_TO_BACK_AVG(BGFX_TOPOLOGY_SORT_DISTANCE_FRONT_TO_BACK_AVG),
    DISTANCE_FRONT_TO_BACK_MAX(BGFX_TOPOLOGY_SORT_DISTANCE_FRONT_TO_BACK_MAX),
    DISTANCE_BACK_TO_FRONT_MIN(BGFX_TOPOLOGY_SORT_DISTANCE_BACK_TO_FRONT_MIN),
    DISTANCE_BACK_TO_FRONT_AVG(BGFX_TOPOLOGY_SORT_DISTANCE_BACK_TO_FRONT_AVG),
    DISTANCE_BACK_TO_FRONT_MAX(BGFX_TOPOLOGY_SORT_DISTANCE_BACK_TO_FRONT_MAX),
    COUNT(BGFX_TOPOLOGY_SORT_COUNT);

    public final int VALUE;

    BGFX_TOPOLOGY_SORT(int value) {
        this.VALUE = value;
    }

    public static long flags(Set<BGFX_TOPOLOGY_SORT> states) {
        long bits = 0L;
        for (BGFX_TOPOLOGY_SORT next : states) {
            bits |= next.VALUE;
        }
        return bits;
    }
}
