package com.bariumhoof.assertions;

import com.bariumhoof.bgfx4j.enums.BGFX_CAPS;
import org.jetbrains.annotations.Contract;

import java.util.Collection;
import java.util.function.Supplier;

// todo make seperate lib
interface AssertionFunctions {

    @Contract("null -> fail")
    void requireNonNull(Object object);
    @Contract("null, _ -> fail")
    void requireNonNull(Object object, String message);
    @Contract("null, _ -> fail")
    void requireNonNull(Object object, Supplier<String> message);
    void requireBgfxInitialized(String reason);
    void require(boolean b);
    void requireIfCapEnabled(boolean b, BGFX_CAPS caps);
    void requireIfCapsEnabled(boolean b, BGFX_CAPS ... caps);
    void requireIfCapDisabled(boolean b, BGFX_CAPS caps);
    void requireIfCapsDisabled(boolean b, BGFX_CAPS ... caps);
    void requireEmpty(Collection<?> c);
    void requireNonEmpty(Collection<?> c);
    void requireNonNegative(byte n);
    void requireNonNegative(short n);
    void requireNonNegative(int n);
    void requireNonNegative(long n);
    void requireNonNegative(float n);
    void requireNonNegative(double n);
    void requireNonNegative(byte n, String message);
    void requireNonNegative(short n, String message);
    void requireNonNegative(int n, String message);
    void requireNonNegative(long n, String message);
    void requireNonNegative(float n, String message);
    void requireNonNegative(double n, String message);
    void requireNonNegative(byte n, Supplier<String> message);
    void requireNonNegative(short n, Supplier<String> message);
    void requireNonNegative(int n, Supplier<String> message);
    void requireNonNegative(long n, Supplier<String> message);
    void requireNonNegative(float n, Supplier<String> message);
    void requireNonNegative(double n, Supplier<String> message);
    void requirePositive(byte n);
    void requirePositive(short n);
    void requirePositive(int n);
    void requirePositive(long n);
    void requirePositive(float n);
    void requirePositive(double n);
    void requirePositive(byte n, String message);
    void requirePositive(short n, String message);
    void requirePositive(int n, String message);
    void requirePositive(long n, String message);
    void requirePositive(float n, String message);
    void requirePositive(double n, String message);
    void requirePositive(byte n, Supplier<String> message);
    void requirePositive(short n, Supplier<String> message);
    void requirePositive(int n, Supplier<String> message);
    void requirePositive(long n, Supplier<String> message);
    void requirePositive(float n, Supplier<String> message);
    void requirePositive(double n, Supplier<String> message);
    void requireLessThan(byte n, byte upperBoundExclusive);
    void requireLessThan(short n, short upperBoundExclusive);
    void requireLessThan(int n, int upperBoundExclusive);
    void requireLessThan(long n, long upperBoundExclusive);
    void requireLessThan(float n, float upperBoundExclusive);
    void requireLessThan(double n, double upperBoundExclusive);
    void requireLessThan(byte n, byte upperBoundExclusive, String message);
    void requireLessThan(short n, short upperBoundExclusive, String message);
    void requireLessThan(int n, int upperBoundExclusive, String message);
    void requireLessThan(long n, long upperBoundExclusive, String message);
    void requireLessThan(float n, float upperBoundExclusive, String message);
    void requireLessThan(double n, double upperBoundExclusive, String message);
    void requireLessThan(byte n, byte upperBoundExclusive, Supplier<String> message);
    void requireLessThan(short n, short upperBoundExclusive, Supplier<String> message);
    void requireLessThan(int n, int upperBoundExclusive, Supplier<String> message);
    void requireLessThan(long n, long upperBoundExclusive, Supplier<String> message);
    void requireLessThan(float n, float upperBoundExclusive, Supplier<String> message);
    void requireLessThan(double n, double upperBoundExclusive, Supplier<String> message);
    void requireGreaterThan(byte n, byte upperBoundExclusive);
    void requireGreaterThan(short n, short upperBoundExclusive);
    void requireGreaterThan(int n, int upperBoundExclusive);
    void requireGreaterThan(long n, long upperBoundExclusive);
    void requireGreaterThan(float n, float upperBoundExclusive);
    void requireGreaterThan(double n, double upperBoundExclusive);
    void requireGreaterThan(byte n, byte upperBoundExclusive, String message);
    void requireGreaterThan(short n, short upperBoundExclusive, String message);
    void requireGreaterThan(int n, int upperBoundExclusive, String message);
    void requireGreaterThan(long n, long upperBoundExclusive, String message);
    void requireGreaterThan(float n, float upperBoundExclusive, String message);
    void requireGreaterThan(double n, double upperBoundExclusive, String message);
    void requireGreaterThan(byte n, byte upperBoundExclusive, Supplier<String> message);
    void requireGreaterThan(short n, short upperBoundExclusive, Supplier<String> message);
    void requireGreaterThan(int n, int upperBoundExclusive, Supplier<String> message);
    void requireGreaterThan(long n, long upperBoundExclusive, Supplier<String> message);
    void requireGreaterThan(float n, float upperBoundExclusive, Supplier<String> message);
    void requireGreaterThan(double n, double upperBoundExclusive, Supplier<String> message);
    void requireLessThanOrEqualTo(byte n, byte upperBoundInclusive);
    void requireLessThanOrEqualTo(short n, short upperBoundInclusive);
    void requireLessThanOrEqualTo(int n, int upperBoundInclusive);
    void requireLessThanOrEqualTo(long n, long upperBoundInclusive);
    void requireLessThanOrEqualTo(float n, float upperBoundInclusive);
    void requireLessThanOrEqualTo(double n, double upperBoundInclusive);
    void requireLessThanOrEqualTo(byte n, byte upperBoundInclusive, String message);
    void requireLessThanOrEqualTo(short n, short upperBoundInclusive, String message);
    void requireLessThanOrEqualTo(int n, int upperBoundInclusive, String message);
    void requireLessThanOrEqualTo(long n, long upperBoundInclusive, String message);
    void requireLessThanOrEqualTo(float n, float upperBoundInclusive, String message);
    void requireLessThanOrEqualTo(double n, double upperBoundInclusive, String message);
    void requireLessThanOrEqualTo(byte n, byte upperBoundInclusive, Supplier<String> message);
    void requireLessThanOrEqualTo(short n, short upperBoundInclusive, Supplier<String> message);
    void requireLessThanOrEqualTo(int n, int upperBoundInclusive, Supplier<String> message);
    void requireLessThanOrEqualTo(long n, long upperBoundInclusive, Supplier<String> message);
    void requireLessThanOrEqualTo(float n, float upperBoundInclusive, Supplier<String> message);
    void requireLessThanOrEqualTo(double n, double upperBoundInclusive, Supplier<String> message);
    void requireGreaterThanOrEqualTo(byte n, byte upperBoundInclusive);
    void requireGreaterThanOrEqualTo(short n, short upperBoundInclusive);
    void requireGreaterThanOrEqualTo(int n, int upperBoundInclusive);
    void requireGreaterThanOrEqualTo(long n, long upperBoundInclusive);
    void requireGreaterThanOrEqualTo(float n, float upperBoundInclusive);
    void requireGreaterThanOrEqualTo(double n, double upperBoundInclusive);
    void requireGreaterThanOrEqualTo(byte n, byte upperBoundInclusive, String message);
    void requireGreaterThanOrEqualTo(short n, short upperBoundInclusive, String message);
    void requireGreaterThanOrEqualTo(int n, int upperBoundInclusive, String message);
    void requireGreaterThanOrEqualTo(long n, long upperBoundInclusive, String message);
    void requireGreaterThanOrEqualTo(float n, float upperBoundInclusive, String message);
    void requireGreaterThanOrEqualTo(double n, double upperBoundInclusive, String message);
    void requireGreaterThanOrEqualTo(byte n, byte upperBoundInclusive, Supplier<String> message);
    void requireGreaterThanOrEqualTo(short n, short upperBoundInclusive, Supplier<String> message);
    void requireGreaterThanOrEqualTo(int n, int upperBoundInclusive, Supplier<String> message);
    void requireGreaterThanOrEqualTo(long n, long upperBoundInclusive, Supplier<String> message);
    void requireGreaterThanOrEqualTo(float n, float upperBoundInclusive, Supplier<String> message);
    void requireGreaterThanOrEqualTo(double n, double upperBoundInclusive, Supplier<String> message);

}
